### PR TITLE
Remove FlatBufferSubmodule

### PR DESCRIPTION
**Pull request by rfernandes**
* Rely on distro/system flatbuffer package instead of submodule

### CODE REVIEW

**Comment by rfernandes** [comment]
This also makes the cppcheck / clang-tidy output cleaner, as many issues were with flatpack itself

**Comment by rfernandes** [comment]
Travis build failed as it requires the aformentioned flatbuffer package

**Comment by marayl** [comment]
I don't think trusty has a package for flatbuffers, which is probably why I opted for submodule originally. If I can't find a solution then we may have to consider an alternate CI solution. Would be a shame to lose the CI build altogether.

**Comment by marayl** [comment]
I've raised #297 to hopefully fix the CI build.

**Comment by marayl** [comment]
I cherry-picked onto my PR and the build now passes, so I'll merge.

**Pull request merged**
